#!/bin/bash


WORKING_DIR=/tiara/home/ithsieh/N1333/working_dir
model_id=$1
DIR_ID='chromosome_'$model_id
rm -rf $DIR_ID.log


 
source $HOME/.load_sparx_module 2>/dev/null

# enter working directory
cd $WORKING_DIR
    cd $DIR_ID
        # generate model
        rm -rf model
        \cp ../../preprocessor/grid.py grid.py
        presparx -o model >> $DIR_ID.log

        # make continuum map @ 355GHz
        rm -rf cont_map*
        sparx run task_contobs \
        source=model \
        out=cont_map \
        wavelen='840um' \
        dist='235pc' \
        cell="['0.3asec','0.3asec']" \
        npix="[32,32]" \
        unit='JY/PIXEL' \
        subres="[['-10asec','-10asec','10asec','10asec',2]]" \
        >/dev/null && echo 'image generated' >> $DIR_ID.log

        # evaluate the luminosities of multiple beam size
        rm -rf beam_luminocity.txt
        for beam_size in 0.25 0.4 0.6 0.8 1.0 1.25  
        do
            rm -rf 'conv_'$beam_size
            convol map=cont_map out='conv_'$beam_size fwhm=$beam_size >/dev/null
            imspect in='conv_'$beam_size region='rel,box(0,0,0,0)' log=tmp.log >/dev/null
            echo $beam_size `tail -n 1 tmp.log \
            | awk -v x=3 '{print $x}'` \
            | tee -a beam_luminocity.txt \
            >/dev/null
        done
# leave the directory
cd ../..
