#!/bin/bash
###### Job name ######
#PBS -N GA
###### Output files ######
#PBS -o GA.out
#PBS -e GA.err
###### Number of nodes and cores ######
#PBS -l nodes=8:ppn=12
###### Queue name ######
#PBS -q medium
###### Specific the shell types ######
#PBS -S /bin/bash

###### Enter this job's working directory ######
PBS_O_WORKDIR=/tiara/home/ithsieh/N1333_GA
cd $PBS_O_WORKDIR

if [ -n "$PBS_NODEFILE" ]; then
  if [ -f $PBS_NODEFILE ]; then
    NPROCS=`wc -l < $PBS_NODEFILE`
  fi
fi

$OPENMPI_HOME/bin/mpirun -v -machinefile $PBS_NODEFILE -np $NPROCS \
python mpiGA.py | tee history.log
